version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        steps: 
            - checkout
            - setup_remote_docker

            - run:
                name: 'Verifying code is checked out'
                command: ls -al
            - run:
                name: 'Install Packages'
                command: yarn install
            - run:
                name: 'Build application'
                command: yarn build:ta
            - run: 
                command: |
                    docker build -t vasanthapuram.azurecr.io/todo:1.0 . 
            - run:
                command: |
                    docker login --username $DOCKER_USER --password $DOCKER_PASS vasanthapuram.azurecr.io
            - run:
                command: | 
                    docker push vasanthapuram.azurecr.io/todo:1.0                    
                    