version: 2.1
jobs:
    build:
        docker:
            - image: alpine:3.7
        steps: 
            - run:
                name: First step
                command: |
                    - echo 'Hello world'    
                    - echo 'This is delivery pipeline'
