version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        steps: 
            - checkout
            - run:
                name: First step
                command: |
                    echo 'Hello world'    
                    echo 'This is delivery pipeline'
            - run:
                name: 'Verifying code is checked out'
                command: ls -al
            - run:
                name: 'Install Packages'
                command: yarn install
            - run:
                name: 'Build application'
                command: yarn build
            - run:
                name: 'Unit Tests'
                command: yarn test
